### ISSUE TITLE
Returning uppercase and lowercase variations with /i

### ISSUE THREAD

**Issue by rafaels-dev** [pocesar/js-diacritic-regex#1]
When regex option "i" is passed, it's not necessary to generate upper and lowercase variations in regex.

Example:
toRegex({ flags: 'i' })('olá') should return /ol[aáàãä]/i;

When flag 'i' is not passed, should return /ol[aAáÁàÀãÃäÄ]/

**Comment by pocesar** [comment]
indeed, but since the flag is an optional thing, it applies to the rest of the string as well (in your example, like OLA, olÁ, Olá, OLÁ etc)
and plus, single char matching is cheap and it's quite performant. and since there's a mapping that supports unicode characters, it wouldn't be the best to 'assume' case sensitiveness from the flag.
